import type { AdvisorLine } from '../types/Advisor';

export const ADVISOR_LINES: AdvisorLine[] = [
    // ── Generic: law × approve ──────────────────────────────────────────────
    { category: 'law', verdict: 'approve', level: 0, key: 'g_law_approve_0_0' },
    { category: 'law', verdict: 'approve', level: 0, key: 'g_law_approve_0_1' },
    { category: 'law', verdict: 'approve', level: 0, key: 'g_law_approve_0_2' },
    { category: 'law', verdict: 'approve', level: 1, key: 'g_law_approve_1_0' },
    { category: 'law', verdict: 'approve', level: 1, key: 'g_law_approve_1_1' },
    { category: 'law', verdict: 'approve', level: 1, key: 'g_law_approve_1_2' },
    { category: 'law', verdict: 'approve', level: 2, key: 'g_law_approve_2_0' },
    { category: 'law', verdict: 'approve', level: 2, key: 'g_law_approve_2_1' },
    { category: 'law', verdict: 'approve', level: 2, key: 'g_law_approve_2_2' },
    { category: 'law', verdict: 'approve', level: 3, key: 'g_law_approve_3_0' },
    { category: 'law', verdict: 'approve', level: 3, key: 'g_law_approve_3_1' },
    { category: 'law', verdict: 'approve', level: 3, key: 'g_law_approve_3_2' },

    // ── Generic: law × reject ───────────────────────────────────────────────
    { category: 'law', verdict: 'reject', level: 0, key: 'g_law_reject_0_0' },
    { category: 'law', verdict: 'reject', level: 0, key: 'g_law_reject_0_1' },
    { category: 'law', verdict: 'reject', level: 0, key: 'g_law_reject_0_2' },
    { category: 'law', verdict: 'reject', level: 1, key: 'g_law_reject_1_0' },
    { category: 'law', verdict: 'reject', level: 1, key: 'g_law_reject_1_1' },
    { category: 'law', verdict: 'reject', level: 1, key: 'g_law_reject_1_2' },
    { category: 'law', verdict: 'reject', level: 2, key: 'g_law_reject_2_0' },
    { category: 'law', verdict: 'reject', level: 2, key: 'g_law_reject_2_1' },
    { category: 'law', verdict: 'reject', level: 2, key: 'g_law_reject_2_2' },
    { category: 'law', verdict: 'reject', level: 3, key: 'g_law_reject_3_0' },
    { category: 'law', verdict: 'reject', level: 3, key: 'g_law_reject_3_1' },
    { category: 'law', verdict: 'reject', level: 3, key: 'g_law_reject_3_2' },

    // ── Generic: deal × approve ─────────────────────────────────────────────
    { category: 'deal', verdict: 'approve', level: 0, key: 'g_deal_approve_0_0' },
    { category: 'deal', verdict: 'approve', level: 0, key: 'g_deal_approve_0_1' },
    { category: 'deal', verdict: 'approve', level: 0, key: 'g_deal_approve_0_2' },
    { category: 'deal', verdict: 'approve', level: 1, key: 'g_deal_approve_1_0' },
    { category: 'deal', verdict: 'approve', level: 1, key: 'g_deal_approve_1_1' },
    { category: 'deal', verdict: 'approve', level: 1, key: 'g_deal_approve_1_2' },
    { category: 'deal', verdict: 'approve', level: 2, key: 'g_deal_approve_2_0' },
    { category: 'deal', verdict: 'approve', level: 2, key: 'g_deal_approve_2_1' },
    { category: 'deal', verdict: 'approve', level: 2, key: 'g_deal_approve_2_2' },
    { category: 'deal', verdict: 'approve', level: 3, key: 'g_deal_approve_3_0' },
    { category: 'deal', verdict: 'approve', level: 3, key: 'g_deal_approve_3_1' },
    { category: 'deal', verdict: 'approve', level: 3, key: 'g_deal_approve_3_2' },

    // ── Generic: deal × reject ──────────────────────────────────────────────
    { category: 'deal', verdict: 'reject', level: 0, key: 'g_deal_reject_0_0' },
    { category: 'deal', verdict: 'reject', level: 0, key: 'g_deal_reject_0_1' },
    { category: 'deal', verdict: 'reject', level: 0, key: 'g_deal_reject_0_2' },
    { category: 'deal', verdict: 'reject', level: 1, key: 'g_deal_reject_1_0' },
    { category: 'deal', verdict: 'reject', level: 1, key: 'g_deal_reject_1_1' },
    { category: 'deal', verdict: 'reject', level: 1, key: 'g_deal_reject_1_2' },
    { category: 'deal', verdict: 'reject', level: 2, key: 'g_deal_reject_2_0' },
    { category: 'deal', verdict: 'reject', level: 2, key: 'g_deal_reject_2_1' },
    { category: 'deal', verdict: 'reject', level: 2, key: 'g_deal_reject_2_2' },
    { category: 'deal', verdict: 'reject', level: 3, key: 'g_deal_reject_3_0' },
    { category: 'deal', verdict: 'reject', level: 3, key: 'g_deal_reject_3_1' },
    { category: 'deal', verdict: 'reject', level: 3, key: 'g_deal_reject_3_2' },

    // ── Generic: budget × warn ──────────────────────────────────────────────
    { category: 'budget', verdict: 'warn', level: 0, key: 'g_budget_warn_0_0' },
    { category: 'budget', verdict: 'warn', level: 0, key: 'g_budget_warn_0_1' },
    { category: 'budget', verdict: 'warn', level: 0, key: 'g_budget_warn_0_2' },
    { category: 'budget', verdict: 'warn', level: 1, key: 'g_budget_warn_1_0' },
    { category: 'budget', verdict: 'warn', level: 1, key: 'g_budget_warn_1_1' },
    { category: 'budget', verdict: 'warn', level: 1, key: 'g_budget_warn_1_2' },
    { category: 'budget', verdict: 'warn', level: 2, key: 'g_budget_warn_2_0' },
    { category: 'budget', verdict: 'warn', level: 2, key: 'g_budget_warn_2_1' },
    { category: 'budget', verdict: 'warn', level: 2, key: 'g_budget_warn_2_2' },
    { category: 'budget', verdict: 'warn', level: 3, key: 'g_budget_warn_3_0' },
    { category: 'budget', verdict: 'warn', level: 3, key: 'g_budget_warn_3_1' },
    { category: 'budget', verdict: 'warn', level: 3, key: 'g_budget_warn_3_2' },

    // ── Generic: budget × ok ────────────────────────────────────────────────
    { category: 'budget', verdict: 'ok', level: 0, key: 'g_budget_ok_0_0' },
    { category: 'budget', verdict: 'ok', level: 0, key: 'g_budget_ok_0_1' },
    { category: 'budget', verdict: 'ok', level: 0, key: 'g_budget_ok_0_2' },
    { category: 'budget', verdict: 'ok', level: 1, key: 'g_budget_ok_1_0' },
    { category: 'budget', verdict: 'ok', level: 1, key: 'g_budget_ok_1_1' },
    { category: 'budget', verdict: 'ok', level: 1, key: 'g_budget_ok_1_2' },
    { category: 'budget', verdict: 'ok', level: 2, key: 'g_budget_ok_2_0' },
    { category: 'budget', verdict: 'ok', level: 2, key: 'g_budget_ok_2_1' },
    { category: 'budget', verdict: 'ok', level: 2, key: 'g_budget_ok_2_2' },
    { category: 'budget', verdict: 'ok', level: 3, key: 'g_budget_ok_3_0' },
    { category: 'budget', verdict: 'ok', level: 3, key: 'g_budget_ok_3_1' },
    { category: 'budget', verdict: 'ok', level: 3, key: 'g_budget_ok_3_2' },

    // ── Generic: dayended × warn ────────────────────────────────────────────
    { category: 'dayended', verdict: 'warn', level: 0, key: 'g_dayended_warn_0_0' },
    { category: 'dayended', verdict: 'warn', level: 0, key: 'g_dayended_warn_0_1' },
    { category: 'dayended', verdict: 'warn', level: 0, key: 'g_dayended_warn_0_2' },
    { category: 'dayended', verdict: 'warn', level: 1, key: 'g_dayended_warn_1_0' },
    { category: 'dayended', verdict: 'warn', level: 1, key: 'g_dayended_warn_1_1' },
    { category: 'dayended', verdict: 'warn', level: 1, key: 'g_dayended_warn_1_2' },
    { category: 'dayended', verdict: 'warn', level: 2, key: 'g_dayended_warn_2_0' },
    { category: 'dayended', verdict: 'warn', level: 2, key: 'g_dayended_warn_2_1' },
    { category: 'dayended', verdict: 'warn', level: 2, key: 'g_dayended_warn_2_2' },
    { category: 'dayended', verdict: 'warn', level: 3, key: 'g_dayended_warn_3_0' },
    { category: 'dayended', verdict: 'warn', level: 3, key: 'g_dayended_warn_3_1' },
    { category: 'dayended', verdict: 'warn', level: 3, key: 'g_dayended_warn_3_2' },

    // ── Generic: dayended × ok ──────────────────────────────────────────────
    { category: 'dayended', verdict: 'ok', level: 0, key: 'g_dayended_ok_0_0' },
    { category: 'dayended', verdict: 'ok', level: 0, key: 'g_dayended_ok_0_1' },
    { category: 'dayended', verdict: 'ok', level: 0, key: 'g_dayended_ok_0_2' },
    { category: 'dayended', verdict: 'ok', level: 1, key: 'g_dayended_ok_1_0' },
    { category: 'dayended', verdict: 'ok', level: 1, key: 'g_dayended_ok_1_1' },
    { category: 'dayended', verdict: 'ok', level: 1, key: 'g_dayended_ok_1_2' },
    { category: 'dayended', verdict: 'ok', level: 2, key: 'g_dayended_ok_2_0' },
    { category: 'dayended', verdict: 'ok', level: 2, key: 'g_dayended_ok_2_1' },
    { category: 'dayended', verdict: 'ok', level: 2, key: 'g_dayended_ok_2_2' },
    { category: 'dayended', verdict: 'ok', level: 3, key: 'g_dayended_ok_3_0' },
    { category: 'dayended', verdict: 'ok', level: 3, key: 'g_dayended_ok_3_1' },
    { category: 'dayended', verdict: 'ok', level: 3, key: 'g_dayended_ok_3_2' },

    // ── Override: coup_warn ─────────────────────────────────────────────────
    { category: 'dayended', verdict: 'warn', level: 0, key: 'o_coup_warn_0_0', trigger: 'coup_warn' },
    { category: 'dayended', verdict: 'warn', level: 0, key: 'o_coup_warn_0_1', trigger: 'coup_warn' },
    { category: 'dayended', verdict: 'warn', level: 0, key: 'o_coup_warn_0_2', trigger: 'coup_warn' },
    { category: 'dayended', verdict: 'warn', level: 0, key: 'o_coup_warn_0_3', trigger: 'coup_warn' },
    { category: 'dayended', verdict: 'warn', level: 1, key: 'o_coup_warn_1_0', trigger: 'coup_warn' },
    { category: 'dayended', verdict: 'warn', level: 1, key: 'o_coup_warn_1_1', trigger: 'coup_warn' },
    { category: 'dayended', verdict: 'warn', level: 1, key: 'o_coup_warn_1_2', trigger: 'coup_warn' },
    { category: 'dayended', verdict: 'warn', level: 1, key: 'o_coup_warn_1_3', trigger: 'coup_warn' },
    { category: 'dayended', verdict: 'warn', level: 2, key: 'o_coup_warn_2_0', trigger: 'coup_warn' },
    { category: 'dayended', verdict: 'warn', level: 2, key: 'o_coup_warn_2_1', trigger: 'coup_warn' },
    { category: 'dayended', verdict: 'warn', level: 2, key: 'o_coup_warn_2_2', trigger: 'coup_warn' },
    { category: 'dayended', verdict: 'warn', level: 2, key: 'o_coup_warn_2_3', trigger: 'coup_warn' },
    { category: 'dayended', verdict: 'warn', level: 3, key: 'o_coup_warn_3_0', trigger: 'coup_warn' },
    { category: 'dayended', verdict: 'warn', level: 3, key: 'o_coup_warn_3_1', trigger: 'coup_warn' },
    { category: 'dayended', verdict: 'warn', level: 3, key: 'o_coup_warn_3_2', trigger: 'coup_warn' },
    { category: 'dayended', verdict: 'warn', level: 3, key: 'o_coup_warn_3_3', trigger: 'coup_warn' },

    // ── Override: law_recurring_income ──────────────────────────────────────
    { category: 'law', verdict: 'approve', level: 0, key: 'o_law_recurring_income_0_0', trigger: 'law_recurring_income' },
    { category: 'law', verdict: 'approve', level: 0, key: 'o_law_recurring_income_0_1', trigger: 'law_recurring_income' },
    { category: 'law', verdict: 'approve', level: 0, key: 'o_law_recurring_income_0_2', trigger: 'law_recurring_income' },
    { category: 'law', verdict: 'approve', level: 0, key: 'o_law_recurring_income_0_3', trigger: 'law_recurring_income' },
    { category: 'law', verdict: 'approve', level: 1, key: 'o_law_recurring_income_1_0', trigger: 'law_recurring_income' },
    { category: 'law', verdict: 'approve', level: 1, key: 'o_law_recurring_income_1_1', trigger: 'law_recurring_income' },
    { category: 'law', verdict: 'approve', level: 1, key: 'o_law_recurring_income_1_2', trigger: 'law_recurring_income' },
    { category: 'law', verdict: 'approve', level: 1, key: 'o_law_recurring_income_1_3', trigger: 'law_recurring_income' },
    { category: 'law', verdict: 'approve', level: 2, key: 'o_law_recurring_income_2_0', trigger: 'law_recurring_income' },
    { category: 'law', verdict: 'approve', level: 2, key: 'o_law_recurring_income_2_1', trigger: 'law_recurring_income' },
    { category: 'law', verdict: 'approve', level: 2, key: 'o_law_recurring_income_2_2', trigger: 'law_recurring_income' },
    { category: 'law', verdict: 'approve', level: 2, key: 'o_law_recurring_income_2_3', trigger: 'law_recurring_income' },
    { category: 'law', verdict: 'approve', level: 3, key: 'o_law_recurring_income_3_0', trigger: 'law_recurring_income' },
    { category: 'law', verdict: 'approve', level: 3, key: 'o_law_recurring_income_3_1', trigger: 'law_recurring_income' },
    { category: 'law', verdict: 'approve', level: 3, key: 'o_law_recurring_income_3_2', trigger: 'law_recurring_income' },
    { category: 'law', verdict: 'approve', level: 3, key: 'o_law_recurring_income_3_3', trigger: 'law_recurring_income' },

    // ── Override: law_recurring_expense ─────────────────────────────────────
    { category: 'law', verdict: 'approve', level: 0, key: 'o_law_recurring_expense_0_0', trigger: 'law_recurring_expense' },
    { category: 'law', verdict: 'approve', level: 0, key: 'o_law_recurring_expense_0_1', trigger: 'law_recurring_expense' },
    { category: 'law', verdict: 'approve', level: 0, key: 'o_law_recurring_expense_0_2', trigger: 'law_recurring_expense' },
    { category: 'law', verdict: 'approve', level: 0, key: 'o_law_recurring_expense_0_3', trigger: 'law_recurring_expense' },
    { category: 'law', verdict: 'approve', level: 1, key: 'o_law_recurring_expense_1_0', trigger: 'law_recurring_expense' },
    { category: 'law', verdict: 'approve', level: 1, key: 'o_law_recurring_expense_1_1', trigger: 'law_recurring_expense' },
    { category: 'law', verdict: 'approve', level: 1, key: 'o_law_recurring_expense_1_2', trigger: 'law_recurring_expense' },
    { category: 'law', verdict: 'approve', level: 1, key: 'o_law_recurring_expense_1_3', trigger: 'law_recurring_expense' },
    { category: 'law', verdict: 'approve', level: 2, key: 'o_law_recurring_expense_2_0', trigger: 'law_recurring_expense' },
    { category: 'law', verdict: 'approve', level: 2, key: 'o_law_recurring_expense_2_1', trigger: 'law_recurring_expense' },
    { category: 'law', verdict: 'approve', level: 2, key: 'o_law_recurring_expense_2_2', trigger: 'law_recurring_expense' },
    { category: 'law', verdict: 'approve', level: 2, key: 'o_law_recurring_expense_2_3', trigger: 'law_recurring_expense' },
    { category: 'law', verdict: 'approve', level: 3, key: 'o_law_recurring_expense_3_0', trigger: 'law_recurring_expense' },
    { category: 'law', verdict: 'approve', level: 3, key: 'o_law_recurring_expense_3_1', trigger: 'law_recurring_expense' },
    { category: 'law', verdict: 'approve', level: 3, key: 'o_law_recurring_expense_3_2', trigger: 'law_recurring_expense' },
    { category: 'law', verdict: 'approve', level: 3, key: 'o_law_recurring_expense_3_3', trigger: 'law_recurring_expense' },

    // ── Override: budget_tax_penalty ────────────────────────────────────────
    { category: 'budget', verdict: 'warn', level: 0, key: 'o_budget_tax_penalty_0_0', trigger: 'budget_tax_penalty' },
    { category: 'budget', verdict: 'warn', level: 0, key: 'o_budget_tax_penalty_0_1', trigger: 'budget_tax_penalty' },
    { category: 'budget', verdict: 'warn', level: 0, key: 'o_budget_tax_penalty_0_2', trigger: 'budget_tax_penalty' },
    { category: 'budget', verdict: 'warn', level: 0, key: 'o_budget_tax_penalty_0_3', trigger: 'budget_tax_penalty' },
    { category: 'budget', verdict: 'warn', level: 1, key: 'o_budget_tax_penalty_1_0', trigger: 'budget_tax_penalty' },
    { category: 'budget', verdict: 'warn', level: 1, key: 'o_budget_tax_penalty_1_1', trigger: 'budget_tax_penalty' },
    { category: 'budget', verdict: 'warn', level: 1, key: 'o_budget_tax_penalty_1_2', trigger: 'budget_tax_penalty' },
    { category: 'budget', verdict: 'warn', level: 1, key: 'o_budget_tax_penalty_1_3', trigger: 'budget_tax_penalty' },
    { category: 'budget', verdict: 'warn', level: 2, key: 'o_budget_tax_penalty_2_0', trigger: 'budget_tax_penalty' },
    { category: 'budget', verdict: 'warn', level: 2, key: 'o_budget_tax_penalty_2_1', trigger: 'budget_tax_penalty' },
    { category: 'budget', verdict: 'warn', level: 2, key: 'o_budget_tax_penalty_2_2', trigger: 'budget_tax_penalty' },
    { category: 'budget', verdict: 'warn', level: 2, key: 'o_budget_tax_penalty_2_3', trigger: 'budget_tax_penalty' },
    { category: 'budget', verdict: 'warn', level: 3, key: 'o_budget_tax_penalty_3_0', trigger: 'budget_tax_penalty' },
    { category: 'budget', verdict: 'warn', level: 3, key: 'o_budget_tax_penalty_3_1', trigger: 'budget_tax_penalty' },
    { category: 'budget', verdict: 'warn', level: 3, key: 'o_budget_tax_penalty_3_2', trigger: 'budget_tax_penalty' },
    { category: 'budget', verdict: 'warn', level: 3, key: 'o_budget_tax_penalty_3_3', trigger: 'budget_tax_penalty' },

    // ── Override: budget_health_low ─────────────────────────────────────────
    { category: 'budget', verdict: 'warn', level: 0, key: 'o_budget_health_low_0_0', trigger: 'budget_health_low' },
    { category: 'budget', verdict: 'warn', level: 0, key: 'o_budget_health_low_0_1', trigger: 'budget_health_low' },
    { category: 'budget', verdict: 'warn', level: 0, key: 'o_budget_health_low_0_2', trigger: 'budget_health_low' },
    { category: 'budget', verdict: 'warn', level: 0, key: 'o_budget_health_low_0_3', trigger: 'budget_health_low' },
    { category: 'budget', verdict: 'warn', level: 1, key: 'o_budget_health_low_1_0', trigger: 'budget_health_low' },
    { category: 'budget', verdict: 'warn', level: 1, key: 'o_budget_health_low_1_1', trigger: 'budget_health_low' },
    { category: 'budget', verdict: 'warn', level: 1, key: 'o_budget_health_low_1_2', trigger: 'budget_health_low' },
    { category: 'budget', verdict: 'warn', level: 1, key: 'o_budget_health_low_1_3', trigger: 'budget_health_low' },
    { category: 'budget', verdict: 'warn', level: 2, key: 'o_budget_health_low_2_0', trigger: 'budget_health_low' },
    { category: 'budget', verdict: 'warn', level: 2, key: 'o_budget_health_low_2_1', trigger: 'budget_health_low' },
    { category: 'budget', verdict: 'warn', level: 2, key: 'o_budget_health_low_2_2', trigger: 'budget_health_low' },
    { category: 'budget', verdict: 'warn', level: 2, key: 'o_budget_health_low_2_3', trigger: 'budget_health_low' },
    { category: 'budget', verdict: 'warn', level: 3, key: 'o_budget_health_low_3_0', trigger: 'budget_health_low' },
    { category: 'budget', verdict: 'warn', level: 3, key: 'o_budget_health_low_3_1', trigger: 'budget_health_low' },
    { category: 'budget', verdict: 'warn', level: 3, key: 'o_budget_health_low_3_2', trigger: 'budget_health_low' },
    { category: 'budget', verdict: 'warn', level: 3, key: 'o_budget_health_low_3_3', trigger: 'budget_health_low' },

    // ── Override: budget_security_low ───────────────────────────────────────
    { category: 'budget', verdict: 'warn', level: 0, key: 'o_budget_security_low_0_0', trigger: 'budget_security_low' },
    { category: 'budget', verdict: 'warn', level: 0, key: 'o_budget_security_low_0_1', trigger: 'budget_security_low' },
    { category: 'budget', verdict: 'warn', level: 0, key: 'o_budget_security_low_0_2', trigger: 'budget_security_low' },
    { category: 'budget', verdict: 'warn', level: 0, key: 'o_budget_security_low_0_3', trigger: 'budget_security_low' },
    { category: 'budget', verdict: 'warn', level: 1, key: 'o_budget_security_low_1_0', trigger: 'budget_security_low' },
    { category: 'budget', verdict: 'warn', level: 1, key: 'o_budget_security_low_1_1', trigger: 'budget_security_low' },
    { category: 'budget', verdict: 'warn', level: 1, key: 'o_budget_security_low_1_2', trigger: 'budget_security_low' },
    { category: 'budget', verdict: 'warn', level: 1, key: 'o_budget_security_low_1_3', trigger: 'budget_security_low' },
    { category: 'budget', verdict: 'warn', level: 2, key: 'o_budget_security_low_2_0', trigger: 'budget_security_low' },
    { category: 'budget', verdict: 'warn', level: 2, key: 'o_budget_security_low_2_1', trigger: 'budget_security_low' },
    { category: 'budget', verdict: 'warn', level: 2, key: 'o_budget_security_low_2_2', trigger: 'budget_security_low' },
    { category: 'budget', verdict: 'warn', level: 2, key: 'o_budget_security_low_2_3', trigger: 'budget_security_low' },
    { category: 'budget', verdict: 'warn', level: 3, key: 'o_budget_security_low_3_0', trigger: 'budget_security_low' },
    { category: 'budget', verdict: 'warn', level: 3, key: 'o_budget_security_low_3_1', trigger: 'budget_security_low' },
    { category: 'budget', verdict: 'warn', level: 3, key: 'o_budget_security_low_3_2', trigger: 'budget_security_low' },
    { category: 'budget', verdict: 'warn', level: 3, key: 'o_budget_security_low_3_3', trigger: 'budget_security_low' },

    // ── Override: budget_military_low ───────────────────────────────────────
    { category: 'budget', verdict: 'warn', level: 0, key: 'o_budget_military_low_0_0', trigger: 'budget_military_low' },
    { category: 'budget', verdict: 'warn', level: 0, key: 'o_budget_military_low_0_1', trigger: 'budget_military_low' },
    { category: 'budget', verdict: 'warn', level: 0, key: 'o_budget_military_low_0_2', trigger: 'budget_military_low' },
    { category: 'budget', verdict: 'warn', level: 0, key: 'o_budget_military_low_0_3', trigger: 'budget_military_low' },
    { category: 'budget', verdict: 'warn', level: 1, key: 'o_budget_military_low_1_0', trigger: 'budget_military_low' },
    { category: 'budget', verdict: 'warn', level: 1, key: 'o_budget_military_low_1_1', trigger: 'budget_military_low' },
    { category: 'budget', verdict: 'warn', level: 1, key: 'o_budget_military_low_1_2', trigger: 'budget_military_low' },
    { category: 'budget', verdict: 'warn', level: 1, key: 'o_budget_military_low_1_3', trigger: 'budget_military_low' },
    { category: 'budget', verdict: 'warn', level: 2, key: 'o_budget_military_low_2_0', trigger: 'budget_military_low' },
    { category: 'budget', verdict: 'warn', level: 2, key: 'o_budget_military_low_2_1', trigger: 'budget_military_low' },
    { category: 'budget', verdict: 'warn', level: 2, key: 'o_budget_military_low_2_2', trigger: 'budget_military_low' },
    { category: 'budget', verdict: 'warn', level: 2, key: 'o_budget_military_low_2_3', trigger: 'budget_military_low' },
    { category: 'budget', verdict: 'warn', level: 3, key: 'o_budget_military_low_3_0', trigger: 'budget_military_low' },
    { category: 'budget', verdict: 'warn', level: 3, key: 'o_budget_military_low_3_1', trigger: 'budget_military_low' },
    { category: 'budget', verdict: 'warn', level: 3, key: 'o_budget_military_low_3_2', trigger: 'budget_military_low' },
    { category: 'budget', verdict: 'warn', level: 3, key: 'o_budget_military_low_3_3', trigger: 'budget_military_low' },

    // ── Override: budget_infra_low ──────────────────────────────────────────
    { category: 'budget', verdict: 'warn', level: 0, key: 'o_budget_infra_low_0_0', trigger: 'budget_infra_low' },
    { category: 'budget', verdict: 'warn', level: 0, key: 'o_budget_infra_low_0_1', trigger: 'budget_infra_low' },
    { category: 'budget', verdict: 'warn', level: 0, key: 'o_budget_infra_low_0_2', trigger: 'budget_infra_low' },
    { category: 'budget', verdict: 'warn', level: 0, key: 'o_budget_infra_low_0_3', trigger: 'budget_infra_low' },
    { category: 'budget', verdict: 'warn', level: 1, key: 'o_budget_infra_low_1_0', trigger: 'budget_infra_low' },
    { category: 'budget', verdict: 'warn', level: 1, key: 'o_budget_infra_low_1_1', trigger: 'budget_infra_low' },
    { category: 'budget', verdict: 'warn', level: 1, key: 'o_budget_infra_low_1_2', trigger: 'budget_infra_low' },
    { category: 'budget', verdict: 'warn', level: 1, key: 'o_budget_infra_low_1_3', trigger: 'budget_infra_low' },
    { category: 'budget', verdict: 'warn', level: 2, key: 'o_budget_infra_low_2_0', trigger: 'budget_infra_low' },
    { category: 'budget', verdict: 'warn', level: 2, key: 'o_budget_infra_low_2_1', trigger: 'budget_infra_low' },
    { category: 'budget', verdict: 'warn', level: 2, key: 'o_budget_infra_low_2_2', trigger: 'budget_infra_low' },
    { category: 'budget', verdict: 'warn', level: 2, key: 'o_budget_infra_low_2_3', trigger: 'budget_infra_low' },
    { category: 'budget', verdict: 'warn', level: 3, key: 'o_budget_infra_low_3_0', trigger: 'budget_infra_low' },
    { category: 'budget', verdict: 'warn', level: 3, key: 'o_budget_infra_low_3_1', trigger: 'budget_infra_low' },
    { category: 'budget', verdict: 'warn', level: 3, key: 'o_budget_infra_low_3_2', trigger: 'budget_infra_low' },
    { category: 'budget', verdict: 'warn', level: 3, key: 'o_budget_infra_low_3_3', trigger: 'budget_infra_low' },

    // ── Override: treasury_low ──────────────────────────────────────────────
    { category: 'dayended', verdict: 'warn', level: 0, key: 'o_treasury_low_0_0', trigger: 'treasury_low' },
    { category: 'dayended', verdict: 'warn', level: 0, key: 'o_treasury_low_0_1', trigger: 'treasury_low' },
    { category: 'dayended', verdict: 'warn', level: 0, key: 'o_treasury_low_0_2', trigger: 'treasury_low' },
    { category: 'dayended', verdict: 'warn', level: 0, key: 'o_treasury_low_0_3', trigger: 'treasury_low' },
    { category: 'dayended', verdict: 'warn', level: 1, key: 'o_treasury_low_1_0', trigger: 'treasury_low' },
    { category: 'dayended', verdict: 'warn', level: 1, key: 'o_treasury_low_1_1', trigger: 'treasury_low' },
    { category: 'dayended', verdict: 'warn', level: 1, key: 'o_treasury_low_1_2', trigger: 'treasury_low' },
    { category: 'dayended', verdict: 'warn', level: 1, key: 'o_treasury_low_1_3', trigger: 'treasury_low' },
    { category: 'dayended', verdict: 'warn', level: 2, key: 'o_treasury_low_2_0', trigger: 'treasury_low' },
    { category: 'dayended', verdict: 'warn', level: 2, key: 'o_treasury_low_2_1', trigger: 'treasury_low' },
    { category: 'dayended', verdict: 'warn', level: 2, key: 'o_treasury_low_2_2', trigger: 'treasury_low' },
    { category: 'dayended', verdict: 'warn', level: 2, key: 'o_treasury_low_2_3', trigger: 'treasury_low' },
    { category: 'dayended', verdict: 'warn', level: 3, key: 'o_treasury_low_3_0', trigger: 'treasury_low' },
    { category: 'dayended', verdict: 'warn', level: 3, key: 'o_treasury_low_3_1', trigger: 'treasury_low' },
    { category: 'dayended', verdict: 'warn', level: 3, key: 'o_treasury_low_3_2', trigger: 'treasury_low' },
    { category: 'dayended', verdict: 'warn', level: 3, key: 'o_treasury_low_3_3', trigger: 'treasury_low' },

    // ── Override: treasury_high ─────────────────────────────────────────────
    { category: 'dayended', verdict: 'ok', level: 0, key: 'o_treasury_high_0_0', trigger: 'treasury_high' },
    { category: 'dayended', verdict: 'ok', level: 0, key: 'o_treasury_high_0_1', trigger: 'treasury_high' },
    { category: 'dayended', verdict: 'ok', level: 0, key: 'o_treasury_high_0_2', trigger: 'treasury_high' },
    { category: 'dayended', verdict: 'ok', level: 0, key: 'o_treasury_high_0_3', trigger: 'treasury_high' },
    { category: 'dayended', verdict: 'ok', level: 1, key: 'o_treasury_high_1_0', trigger: 'treasury_high' },
    { category: 'dayended', verdict: 'ok', level: 1, key: 'o_treasury_high_1_1', trigger: 'treasury_high' },
    { category: 'dayended', verdict: 'ok', level: 1, key: 'o_treasury_high_1_2', trigger: 'treasury_high' },
    { category: 'dayended', verdict: 'ok', level: 1, key: 'o_treasury_high_1_3', trigger: 'treasury_high' },
    { category: 'dayended', verdict: 'ok', level: 2, key: 'o_treasury_high_2_0', trigger: 'treasury_high' },
    { category: 'dayended', verdict: 'ok', level: 2, key: 'o_treasury_high_2_1', trigger: 'treasury_high' },
    { category: 'dayended', verdict: 'ok', level: 2, key: 'o_treasury_high_2_2', trigger: 'treasury_high' },
    { category: 'dayended', verdict: 'ok', level: 2, key: 'o_treasury_high_2_3', trigger: 'treasury_high' },
    { category: 'dayended', verdict: 'ok', level: 3, key: 'o_treasury_high_3_0', trigger: 'treasury_high' },
    { category: 'dayended', verdict: 'ok', level: 3, key: 'o_treasury_high_3_1', trigger: 'treasury_high' },
    { category: 'dayended', verdict: 'ok', level: 3, key: 'o_treasury_high_3_2', trigger: 'treasury_high' },
    { category: 'dayended', verdict: 'ok', level: 3, key: 'o_treasury_high_3_3', trigger: 'treasury_high' },
];
